name: Release NuGet

on:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: windows-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    
    - uses: actions/checkout@v1

    - name: Build Project
      run: ./build.ps1
      shell: powershell

    - uses: actions/upload-artifact@master
      with:
        name: NugetPackage
        path: artifacts
        
    - name: Publish NuGet Package (NuGet.org)
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${API_KEY}

    - name: Publish NuGet Package (GitHub)
      env:
        API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push ./artifacts/*.nupkg -k ${API_KEY} --source "https://nuget.pkg.github.com/redth-org/index.json"